### ISSUE TITLE
Official releases

### ISSUE THREAD

**Issue by SnarkBoojum** [PilzAdam/nether#11]
Hi,

I'm considering packaging nether for the Debian distribution, but I would prefer packaging an official release rather than a random git commit.

Could you tag releases for me? Tags like YYYYMMDD is nice if you don't want to play with complex schemes.

Thanks!

**Comment by sofar** [comment]
Maybe once we figure out the teleport/voxelmanip stuff, ok?

**Comment by paramat** [comment]
Yes this mod is not in a good way, best wait until i've made my changes.

**Comment by sofar** [comment]
I've tagged v1. The numbers don't mean much other than that it "should" be stable. The next tag will be "v2".
