### ISSUE TITLE
Voxelmanip branch

### ISSUE THREAD

**Issue by paramat** [PilzAdam/nether#12]
Why are people working on the master branch when the voxelmanip branch has a far better way to generate nether? The 'on generated' function in the voxelmanip branch should be moved into master branch.

**Comment by paramat** [comment]
This is what i have so far, just a start https://gist.github.com/paramat/2c9c3ad9b1a4f0ba9e2385c7170958ba

**Comment by sofar** [comment]
Stale branches are stale. Might as well remove them or merge them.

**Comment by sofar** [comment]
I can merge changes - he gave me push access.

**Comment by paramat** [comment]
Ok good. I'll keep a changelog to be clear what's changed.

**Comment by paramat** [comment]
Great, i'll make a PR to move the voxelmanip stuff into master branch.

**Comment by paramat** [comment]
#13
