### ISSUE TITLE
Nether needs large caves.

### ISSUE THREAD

**Issue by sofar** [PilzAdam/nether#14]
The nether is very, very boring and the chambers are really small. It needs some form of cavegen or supercaves.

**Comment by sofar** [comment]
@paramat any ideas on this one?

**Comment by paramat** [comment]
Was just thinking about this, i have just the thing, fairly simple using 1 3D noise.
Will make a PR.

**Comment by HybridDog** [comment]
Both represent, at least by their name, their derivation from minecraft.
What's the sense of making two nether mods?
![screenshot_20160525_094449](https://cloud.githubusercontent.com/assets/3192173/15531939/6b1ed3f4-225d-11e6-9e6d-27aed8501a10.png)

**Comment by sofar** [comment]
@HybridDog as usual, I can't follow you. I know you have your own nether mod fork, but that does not solve the problem.

**Comment by HybridDog** [comment]
How about making the caves look like crevices by using two perlin noises?

**Comment by paramat** [comment]
During experimentation with large empty spaces i find the player will often fall through the portal, as if the portal generates too late. The destination nether portal will have to be placed on a cavern floor using noise prediction. Hopefully further experimentation will be able to generate the portal before the player teleports. However the portal being on a cavern floor is desirable so i will try this anyway.

**Comment by paramat** [comment]
Should these new caverns be optional? Is anyone desperate to preserve existing worlds?

**Comment by paramat** [comment]
WIP but you can test new caverns here #17
